
language: objective-c
osx_image: xcode7.1
before_install: rvm use $RVM_RUBY_VERSION
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install slather
script:
- set -o pipefail && xcodebuild test -project MSAddition.xcodeproj -scheme MSAddition -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --no-clean
after_success: slather
