language: objective-c
osx_image: xcode11

stages:
- name: test

jobs:
  include:
    - stage: test
      name: "Unit tests"
      xcode_project: MSAddition.xcodeproj
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8
      xcode_scheme: MSAddition
      after_success: bundle exec slather

    - name:  "Validate podspec"
      script: bundle exec pod lib lint

cache: bundler
